name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DEBUG: ${{ secrets.DEBUG }}
  DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      
      
      run: |
        # echo "Checking if ADMIN_USER_ID is set"
        # if [ -z "$ADMIN_USER_ID" ]; then
        # echo "ADMIN_USER_ID is not set"
        # else
        # echo "ADMIN_USER_ID is set"
        # fi
        echo "Checking if DATABASE_URL is set"
        if [ -z "$DATABASE_URL" ]; then
        echo "DATABASE_URL is not set"
        else
        echo "DATABASE_URL is set"
        fi
        # echo "Checking if SENTRY_DSN is set"
        # if [ -z "$SENTRY_DSN" ]; then
        # echo "SENTRY_DSN is not set"
        # else
        # echo "SENTRY_DSN is set"
        # fi
        echo "Checking environment variables"
        env | grep -vE '^(PATH|HOME|RUNNER|GITHUB_)='
        python manage.py test
